--- src2/linux-source-2.6.28/Makefile	2009-11-11 11:47:01.000000000 +0200
+++ src/linux-source-2.6.28/Makefile	2009-11-24 21:05:24.000000000 +0200
@@ -633,7 +633,7 @@
 
 
 ifeq ($(KBUILD_EXTMOD),)
-core-y		+= kernel/ mm/ fs/ ipc/ security/ crypto/ block/
+core-y		+= kernel/ mm/ fs/ ipc/ security/ crypto/ block/ mycall/
 
 vmlinux-dirs	:= $(patsubst %/,%,$(filter %/, $(init-y) $(init-m) \
 		     $(core-y) $(core-m) $(drivers-y) $(drivers-m) \
